config/routes.rb
Offerletter::Application.routes.draw do
  resources :exams

  resources :questions, only: [:show, :edit, :update] do
    resources :solutions
  end

  devise_for :users,
             controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users , only: [:show, :edit, :update, :index] do
    get :revive
  end

  #post 'users/:id/revive' => 'users#revive', as: :users_revive

  root to: 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/modals/_signin.html.erb
<div class="well">

  <h3 style="text-align:center"><b>Brook & Ivan</b> Adventures</h3>

  <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div><%= f.email_field :email, class: "form-control", :autofocus => true, :placeholder => "email" %></div>

  <div><%= f.password_field :password, class: "form-control", :placeholder => "password" %></div>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "signin-text" %><br />
  <% end -%>

  <% if devise_mapping.rememberable? -%>
  <div class="checkbox"><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
  <% end %>

  <div><%= f.submit "Sign in", class: "btn btn-block" %></div>
  <% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
<%= link_to "Don't have an account?", new_registration_path(resource_name), class: "signin-text" %><br />
<% end -%>

<li class="divider"></li>

<%= render "devise/shared/links" %>

</div>

app/views/layouts/modals/_signup.html.erb
<div class="well">
    <h3 style="text-align:center"><b>Brook & Ivan</b> Adventures</h3>

  <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.email_field :email, class: "form-control", :autofocus => true, :placeholder => "email" %></div>

  <div><%= f.password_field :password, class: "form-control", :placeholder => "password" %></div>

  <div><%= f.password_field :password_confirmation, class: "form-control", :placeholder => "password confirmation" %></div>

  <div><%= f.submit "Sign up", class: "btn btn-block" %></div>
  <% end %>

<li class="divider"></li>

<%= render "devise/shared/links" %>

</div>