config/routes.rb
Offerletter::Application.routes.draw do
  resources :exams

  resources :questions, only: [:show, :edit, :update] do
    resources :solutions
  end

  devise_for :users,
             controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users , only: [:show, :edit, :update, :index] do
    get :revive
  end

  #post 'users/:id/revive' => 'users#revive', as: :users_revive

  root to: 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true
  validates :experience, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
  validates :name, presence: true
  validates :questions, presence: true

  def next_question(user)
    if questions.size == user.questions
      nil
    else
      (questions - user.questions).first
    end
  end

  def generate_score(user)
    score = 0
    t = user.questions & questions
    if t.size == 0
      return 'none'
    else
      t.each do |a|
        s = a.solutions & user.solutions
        s.each do |d|
          if d.correct?
            score+=1
          end
        end
      end
      return ((score / questions.size.to_f) * 100).round(2)
    end
  end

  def generate_experience(user)
    (self.experience * (generate_score(user) / 100)).round(1)
  end

  def generate_progress(user)
    ((user.questions.where(exam_id: self.id).length.to_f) / (questions.size)) * 100
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /exams
  # GET /exams.json
  def index
    @exams = policy_scope(Exam).sort! { |a,b| a.level <=> b.level }
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
    1.times do
      question = @exam.questions.build
      5.times { question.answers.build }
    end

    unless current_user.try(:admin?)
      flash[:alert] = "You are not authorized to view this page."
      redirect_to root_path
    end
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)
    authorize @exam
    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render action: 'show', status: :created, location: @exam }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    authorize @exam
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    authorize @exam
    respond_to do |format|
      format.html { redirect_to exams_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:name, :level, :description, :experience,
        questions_attributes: [:id, :exam_id, :content, '_destroy',
        answers_attributes: [:id, :question_id, :content, :correct, '_destroy' ] ])
    end
  end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_answer_fields.html.erb
<fieldset>
  <%= f.text_field :content, class:"form-control", placeholder: "Insert answer" %>
  <%= f.hidden_field :_destroy %>
  <%= f.check_box :correct %>
  <%= f.label :correct, "correct answer?"%>
  <%= link_to "remove answer", '#', class: "remove_fields pull-right btn btn-danger btn-xs" %>
</fieldset>

app/views/exams/_form.html.erb
<%= form_for(@exam) do |f| %>
<% if @exam.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

  <ul>
    <% @exam.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="container">
  <h3 style="text-align: center;">New Exam</h3>
  <div class="well col-md-8 col-md-offset-2">

    <div class="field">
      <%= f.text_field :name, class:"form-control", placeholder: "name", :maxlength => 29 %>
    </div>
    <br />

    <fieldform class="col-md-12 col-md-offset-3">
      <%= f.label :experience, "Experience points" %>
      <%= f.number_field :experience, class:"form-control-right", placeholder: "Values from 1 to 1000"  %>
      <%= f.label :level, "Difficulty level" %>
      <%= f.select :level, 1..9, class:"form-control" %>
    </fieldform>
    <br>
    <br>


    <%= f.fields_for :questions do |builder| %>
    <%= render 'question_fields', f: builder %>
    <% end %>

    <%= link_to_add_fields "Add Question", f, :questions %>

    <div class="actions">
      <%= link_to 'Back', exams_path, class: "btn btn-default form-back" %><%= f.submit "Submit", class: "btn btn-primary form-back" %>
    </div>
    <% end %>
  </div> <!-- well -->
</div> <!-- container -->

app/views/exams/_question_fields.html.erb
<fieldset>
  <%= f.text_area :content, class:"form-control", placeholder:"Insert question" %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "Remove Question", '#', class: "remove_fields btn btn-warning btn-xs" %>
  <%= f.fields_for :answers do |builder| %>
          <%= render 'answer_fields', f: builder %>
  <% end %>

  <%= link_to_add_fields "Add Answer", f, :answers %>

</fieldset>

app/views/exams/edit.html.erb
<div class="container">
    <div class="well-test col-md-6">
      <h3>Editing exam</h3>

      <%= render 'form' %>

    </div>
</div>

app/views/exams/index.html.erb
<body id="mountain">
  <div class='container exams'>
    <div class='row'>
      <% @exams.each do |exam| %>

      <div class='col-lg-4'>
        <div class='well'>
          <h4><b><%= exam.name %></b></h4>
          <h4></h4>>Level: <%= exam.level %> </h4>
          <h4><b>Rewards:</b></h4>
          <h4>Experience: <%= exam.experience %> </h4>
          <% if current_user.present? %>
            <h4>Score: <%= exam.generate_score(current_user) %> </h4>
            <div class ="text-center">
              <% if exam.next_question(current_user) %>
              <%= link_to 'Begin Quest', new_question_solution_path(exam.questions.first), class: "btn btn-info" %>
              <% else %>
              <%= link_to 'Quest completed', '', class: "btn btn-warning" %>
              <% end %>

              <% if policy(exam).update? %>
              <%= link_to 'Edit', edit_exam_path(exam), class: "btn btn-primary" %>
              <% end %>
              <% if policy(exam).destroy? %>
              <%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</body>

app/views/exams/new.html.erb
<div class="container">
  <div class="well-test col-md-6">
    <% if current_user.try(:admin?) %>

    <%= render 'form' %>

    <% end %>
  </div>
</div>

app/views/exams/show.html.erb
<div class="container">
  <div class="well-test col-md-6">
<h2><%= @exam.name %></h2>
<ol>
  <% for question in @exam.questions %>
  <li><%= h question.content %></li>
  <ul>
    <% for answer in question.answers %>
    <li><%= h answer.content %></li>
    <% end %>
  </ul>
  <% end %>
</ol>

<% if current_user.try(:admin?) %>
  <%= link_to 'Edit', edit_exam_path(@exam), class: "btn btn-info" %>
<% end %>

<%= link_to 'Back', exams_path, class: "btn btn-primary" %>
</div>
</div>