config/routes.rb
Offerletter::Application.routes.draw do
  resources :exams

  resources :questions, only: [:show, :edit, :update] do
    resources :solutions
  end

  devise_for :users,
             controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users , only: [:show, :edit, :update, :index] do
    get :revive
  end

  #post 'users/:id/revive' => 'users#revive', as: :users_revive

  root to: 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_flash.html.erb
  <!-- bootstrap flash -->
  <div class="container">
  <% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-default navbar-fixed-bottom" style="border-right-width: 20px;
padding-left: 20px";>
  <ul class="nav navbar-nav">
    <li>
      <%= link_to 'Contact', '#' %>
    </li>
    <li>
      <%= link_to 'About', page_path('about') %>
    </li>
  </ul>
  <ul class="nav navbar-nav pull-right">
    <li>
      <%= link_to 'Made in Seattle', id:"footer-made" %>
    </li>
    <li>
      <%= link_to '© 2013 B&I Adventures', id:"footer-copy" %>
    </li>
  </ul>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "<b>Brook & Ivan</b> Adventures".html_safe, root_path, :class => "navbar-brand"%>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Quests', exams_path %>
        </li>
        <li>
          <%= link_to 'Leaderboard', users_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
        <li class="<%= 'active' if current_page?('#')%> dropdown">
          <%= link_to (current_user.name.to_s + '<b class="caret"></b>').html_safe, @user, :id => 'setupdrop', :class => "dropdown-toggle nav-link", :data => {:toggle => "dropdown"} %>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <li class="divider"></li>
            <% if current_user.admin? %>
            <li><%= link_to 'Create Exam', new_exam_path %></li>
            <% end %>
            <li><%= link_to "Help", '#' %></li>
          </ul>
        </li>
        <% else %>
        <!-- Button trigger modal -->
        <li>
          <%= link_to "Sign In", "#signin", "data-toggle" => "modal", :class => "btn btn-clear" %></li>
        <!-- Modal -->
        <div class="modal fade" id="signin" tabindex="-1" role="dialog" aria-labelledby="signinLabel" aria-hidden="true">
          <div class="modal-dialog">
            <%= render "layouts/modals/signin" %>
          </div>
        </div>
        <!-- Button trigger modal -->
        <li>
          <%= link_to "Create Account", "#signup", "data-toggle" => "modal", :class => "btn btn-primary", :id => "create-account" %></li>
        <div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="signinLabel" aria-hidden="true">
          <div class="modal-dialog">
            <%= render "layouts/modals/signup" %>
            <% end %>
          </div>
        </div><!-- /.modal -->
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_signin.html.erb
<div class="well-center">

  <h2>Sign in</h2>

  <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div><%= f.label :email %><br />
    <%= f.email_field :email, class: "form-control", :autofocus => true %>
  </div>

  <div>
    <%= f.label :password %><br />
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <% if devise_mapping.rememberable? -%>
  <div class="checkbox"><%= f.check_box :remember_me %>
    <%= f.label :remember_me %>
  </div>
  <% end %>

  <div>
    <%= f.submit "Sign in", class: "btn btn-block" %>
  </div>
  <% end %>

  <%= render "devise/shared/links" %>
</div>

app/views/layouts/_signup.html.erb
<div class="well-center">

  <h2>Sign up</h2>

  <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>

    <%= devise_error_messages! %>

    <div>
      <%= f.label :email %><br />
      <%= f.email_field :email, class: "form-control", :autofocus => true %>
    </div>

    <div>
      <%= f.label :password %><br />
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <div>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    </br>

    <div>
      <%= f.submit "Sign up", class: "btn btn-block" %>
    </div>

    </br>
  <% end %>
  <%= render "devise/shared/links" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brook & Ivan's Adventures</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/flash' %>
<%= render 'layouts/header' %>
<%= yield %>
</body>
</html>